global:
  # with this false, you cannot use item names, but you can use custom blocks
  # GLOBAL ONLY
  use-match-material: true
  chest-loot:
    DIAMOND_PICKAXE,1:
      stack-size: 1
      chance: .5
    DIAMOND_PICKAXE,2:
      stack-size: 1
      chance: 1
      DURABILITY: 3
    APPLE:
      stack-size: 1
      chance: 1
    CAKE:
      stack-size: 1
      chance: 1
    EXP_BOTTLE:
      stack-size: 1
      chance: 1
    COAL:
      stack-size: 1
      chance: 1
  sponsor-loot:

chests:
#  example:
#    inherits: example1
#    DIAMOND_PICKAXE,1:
#      stack-size: 1
#      # chance is not needed, without it, it defaults to 1/3.
#      # 1 is always, 0 is never
#      chance: .5
#    DIAMOND_PICKAXE,2:
#      stack-size: 1
#      chance: 1
#      DURABILITY: 3

itemsets:
# Example game
# To use one of these, when creating a game do 
# /hga add itemset <name-of-game> <name-of-itemset>  NOTE make sure there are no space in the list of itemsets
#  test:
#   inherits: itemset1
#	  chest-loot:
#           # Note DURABIlITY is an enchantment
#           # anything after a comma is ignored and is only there so you can have multiple of the same item. 
#           # Items added by code will have a generated number after it. Ignore it.
#	    278,1:
#           stack-size: 1
#	      chance: 0.01
#	      DURABILITY: 3
#         sponsor-loot:
#	    278,1:
#             stack-size: 1
#	      money: 10.00
#	      DURABILITY: 3

rewards:
  # Every one of the below will be given
  static:
#    DIAMOND_PICKAXE,1:
#      stack-size: 1
#      DURABILITY: 3
  # The max amount of items that can be given to a player randomly
  max-random: 5
  # The following will be randomly given to the player
  random:
#   278,1:
#     stack-size: 1
#       chance: 0.01
#       DURABILITY: 3

kits:
   # Example
#  test:
#    DIAMOND_PICKAXE,1:
#      stack-size: 1
#      DURABILITY: 3